package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class AboutArticle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.flag
     *
     * @mbggenerated
     */
    private String flag = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column about_article_tbl.content
     *
     * @mbggenerated
     */
    private String content;
    
    private String brandType;
    
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    public AboutArticle(Integer id, Date createTime, String createUser, String flag, 
    		String category, String content,String brandType,String language) {
        this.id = id;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.category = category;
        this.content = content;
        this.brandType = brandType;
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    public AboutArticle() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.id
     *
     * @return the value of about_article_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.id
     *
     * @param id the value for about_article_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.create_time
     *
     * @return the value of about_article_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.create_time
     *
     * @param createTime the value for about_article_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.create_user
     *
     * @return the value of about_article_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.create_user
     *
     * @param createUser the value for about_article_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.flag
     *
     * @return the value of about_article_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.flag
     *
     * @param flag the value for about_article_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.category
     *
     * @return the value of about_article_tbl.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.category
     *
     * @param category the value for about_article_tbl.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column about_article_tbl.content
     *
     * @return the value of about_article_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column about_article_tbl.content
     *
     * @param content the value for about_article_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getBrandType() {
		return brandType;
	}

	public void setBrandType(String brandType) {
		this.brandType = brandType == null ? null : brandType.trim();;
	}
	
	public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language==null?"":language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AboutArticle other = (AboutArticle) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getBrandType() == null ? other.getBrandType() == null : this.getBrandType().equals(other.getBrandType()))
            && (this.getLanguage() == null ? other.getLanguage() == null : this.getLanguage().equals(other.getLanguage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getBrandType() == null) ? 0 : getBrandType().hashCode());
        result = prime * result + ((getLanguage() == null) ? 0 : getLanguage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", category=").append(category);
        sb.append(", content=").append(content);
        sb.append(", brandType=").append(brandType);
        sb.append(", language=").append(language);
        sb.append("]");
        return sb.toString();
    }
    
    public static enum ArticleType{//主题类别
    	
    	CHEERWIN_BRAND_PROFILE("brand_profile"),//超威日化
    	CHEERWIN_GET_HONOR("honor"),//荣誉
    	CHEERWIN_VISION_VALUES("vision_values"),//价值观

    	SUPERB_BRAND_PROFILE("brand_profile"),//超威品牌简介
		
    	BEIBEIJ_BRAND_PROFILE("brand_profile"),//贝贝健品牌简介
		BEIBEIJ_EXCITING_ACTIVITIES("exciting_activities"),//精彩活动
		
		XILAN_BRAND_PROFILE("brand_profile"),//西兰品牌简介
		XILAN_DISCOVERY("discovery"),//发现之旅
		XILAN_INCENSE_TEST("incense_test"), //寻香测试
		XILAN_AROMA("aroma"),//香气百科
		
		VEWIN_BRAND_PROFILE("brand_profile"),//威王品牌简介
    	
    	CONTACT_US("contact_us"),
    	ABOUT_US("aboutUs"),
    	
    	INTRODUCTION("introduction");//企业简介

    	ArticleType(String value) {
			this.value = value;
		}

		private final String value;

		public String toString() {
			return value;
		}
    }
}