package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class Brand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.pic_src
     *
     * @mbggenerated
     */
    private String picSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.banner_pic
     *
     * @mbggenerated
     */
    private String bannerPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.brand_image
     *
     * @mbggenerated
     */
    private String brandImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.brand_desc
     *
     * @mbggenerated
     */
    private String brandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.brand_outline
     *
     * @mbggenerated
     */
    private String brandOutline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    private String weiboId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_tbl.brandType
     *
     * @mbggenerated
     */
    private String brandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    public Brand(Integer id, String brand, String picSrc, String bannerPic, String brandImage, String brandDesc, String brandOutline, String url, Date createTime, String createUser, String flag, String weiboId, String brandType) {
        this.id = id;
        this.brand = brand;
        this.picSrc = picSrc;
        this.bannerPic = bannerPic;
        this.brandImage = brandImage;
        this.brandDesc = brandDesc;
        this.brandOutline = brandOutline;
        this.url = url;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.weiboId = weiboId;
        this.brandType = brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    public Brand() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.id
     *
     * @return the value of brand_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.id
     *
     * @param id the value for brand_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.brand
     *
     * @return the value of brand_tbl.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.brand
     *
     * @param brand the value for brand_tbl.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.pic_src
     *
     * @return the value of brand_tbl.pic_src
     *
     * @mbggenerated
     */
    public String getPicSrc() {
        return picSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.pic_src
     *
     * @param picSrc the value for brand_tbl.pic_src
     *
     * @mbggenerated
     */
    public void setPicSrc(String picSrc) {
        this.picSrc = picSrc == null ? null : picSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.banner_pic
     *
     * @return the value of brand_tbl.banner_pic
     *
     * @mbggenerated
     */
    public String getBannerPic() {
        return bannerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.banner_pic
     *
     * @param bannerPic the value for brand_tbl.banner_pic
     *
     * @mbggenerated
     */
    public void setBannerPic(String bannerPic) {
        this.bannerPic = bannerPic == null ? null : bannerPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.brand_image
     *
     * @return the value of brand_tbl.brand_image
     *
     * @mbggenerated
     */
    public String getBrandImage() {
        return brandImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.brand_image
     *
     * @param brandImage the value for brand_tbl.brand_image
     *
     * @mbggenerated
     */
    public void setBrandImage(String brandImage) {
        this.brandImage = brandImage == null ? null : brandImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.brand_desc
     *
     * @return the value of brand_tbl.brand_desc
     *
     * @mbggenerated
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.brand_desc
     *
     * @param brandDesc the value for brand_tbl.brand_desc
     *
     * @mbggenerated
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc == null ? null : brandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.brand_outline
     *
     * @return the value of brand_tbl.brand_outline
     *
     * @mbggenerated
     */
    public String getBrandOutline() {
        return brandOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.brand_outline
     *
     * @param brandOutline the value for brand_tbl.brand_outline
     *
     * @mbggenerated
     */
    public void setBrandOutline(String brandOutline) {
        this.brandOutline = brandOutline == null ? null : brandOutline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.url
     *
     * @return the value of brand_tbl.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.url
     *
     * @param url the value for brand_tbl.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.create_time
     *
     * @return the value of brand_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.create_time
     *
     * @param createTime the value for brand_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.create_user
     *
     * @return the value of brand_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.create_user
     *
     * @param createUser the value for brand_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.flag
     *
     * @return the value of brand_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.flag
     *
     * @param flag the value for brand_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_tbl.weibo_id
     *
     * @return the value of brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    public String getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_tbl.weibo_id
     *
     * @param weiboId the value for brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    public void setWeiboId(String weiboId) {
        this.weiboId = weiboId == null ? null : weiboId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Brand other = (Brand) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getPicSrc() == null ? other.getPicSrc() == null : this.getPicSrc().equals(other.getPicSrc()))
            && (this.getBannerPic() == null ? other.getBannerPic() == null : this.getBannerPic().equals(other.getBannerPic()))
            && (this.getBrandImage() == null ? other.getBrandImage() == null : this.getBrandImage().equals(other.getBrandImage()))
            && (this.getBrandDesc() == null ? other.getBrandDesc() == null : this.getBrandDesc().equals(other.getBrandDesc()))
            && (this.getBrandOutline() == null ? other.getBrandOutline() == null : this.getBrandOutline().equals(other.getBrandOutline()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getWeiboId() == null ? other.getWeiboId() == null : this.getWeiboId().equals(other.getWeiboId()))
            && (this.getBrandType() == null ? other.getBrandType() == null : this.getBrandType().equals(other.getBrandType()));
    }

    public String getBrandType() {
		return brandType;
	}

	public void setBrandType(String brandType) {
		this.brandType = brandType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getPicSrc() == null) ? 0 : getPicSrc().hashCode());
        result = prime * result + ((getBannerPic() == null) ? 0 : getBannerPic().hashCode());
        result = prime * result + ((getBrandImage() == null) ? 0 : getBrandImage().hashCode());
        result = prime * result + ((getBrandDesc() == null) ? 0 : getBrandDesc().hashCode());
        result = prime * result + ((getBrandOutline() == null) ? 0 : getBrandOutline().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getWeiboId() == null) ? 0 : getWeiboId().hashCode());
        result = prime * result + ((getBrandType() == null) ? 0 : getBrandType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand=").append(brand);
        sb.append(", picSrc=").append(picSrc);
        sb.append(", bannerPic=").append(bannerPic);
        sb.append(", brandImage=").append(brandImage);
        sb.append(", brandDesc=").append(brandDesc);
        sb.append(", brandOutline=").append(brandOutline);
        sb.append(", url=").append(url);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", weiboId=").append(weiboId);
        sb.append(", brandType=").append(brandType);
        sb.append("]");
        return sb.toString();
    }
}