package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class BrandVideo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.year_m
     *
     * @mbggenerated
     */
    private Integer yearM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.youku_id
     *
     * @mbggenerated
     */
    private String youkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.flag
     *
     * @mbggenerated
     */
    private String flag = "1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.title
     *
     * @mbggenerated
     */
    private String title;
    
    private String brandType;
    
    private String category;//类型
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_video_tbl.desc
     *
     * @mbggenerated
     */
    private String videoDesc;

	public String getVideoDesc() {
		return videoDesc;
	}

	public void setVideoDesc(String videoDesc) {
		this.videoDesc = videoDesc;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    public BrandVideo(Integer id, String picture, String videoUrl, 
    		Integer yearM, Integer brandId, Date createTime, 
    		String createUser, String youkuId, String flag, String title,
    		String brandType,String category, String videoDesc) {
        this.id = id;
        this.picture = picture;
        this.videoUrl = videoUrl;
        this.yearM = yearM;
        this.brandId = brandId;
        this.createTime = createTime;
        this.createUser = createUser;
        this.youkuId = youkuId;
        this.flag = flag;
        this.title = title;
        this.brandType = brandType;
        this.category = category;
        this.videoDesc = videoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    public BrandVideo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.id
     *
     * @return the value of brand_video_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.id
     *
     * @param id the value for brand_video_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.picture
     *
     * @return the value of brand_video_tbl.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.picture
     *
     * @param picture the value for brand_video_tbl.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.video_url
     *
     * @return the value of brand_video_tbl.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.video_url
     *
     * @param videoUrl the value for brand_video_tbl.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.year_m
     *
     * @return the value of brand_video_tbl.year_m
     *
     * @mbggenerated
     */
    public Integer getYearM() {
        return yearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.year_m
     *
     * @param yearM the value for brand_video_tbl.year_m
     *
     * @mbggenerated
     */
    public void setYearM(Integer yearM) {
        this.yearM = yearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.brand_id
     *
     * @return the value of brand_video_tbl.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.brand_id
     *
     * @param brandId the value for brand_video_tbl.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.create_time
     *
     * @return the value of brand_video_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.create_time
     *
     * @param createTime the value for brand_video_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.create_user
     *
     * @return the value of brand_video_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.create_user
     *
     * @param createUser the value for brand_video_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.youku_id
     *
     * @return the value of brand_video_tbl.youku_id
     *
     * @mbggenerated
     */
    public String getYoukuId() {
        return youkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.youku_id
     *
     * @param youkuId the value for brand_video_tbl.youku_id
     *
     * @mbggenerated
     */
    public void setYoukuId(String youkuId) {
        this.youkuId = youkuId == null ? null : youkuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.flag
     *
     * @return the value of brand_video_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.flag
     *
     * @param flag the value for brand_video_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_video_tbl.title
     *
     * @return the value of brand_video_tbl.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_video_tbl.title
     *
     * @param title the value for brand_video_tbl.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    
    public String getBrandType() {
		return brandType;
	}

	public void setBrandType(String brandType) {
		this.brandType = brandType==null?null:brandType.trim();
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category==null?null:category.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrandVideo other = (BrandVideo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
            && (this.getVideoUrl() == null ? other.getVideoUrl() == null : this.getVideoUrl().equals(other.getVideoUrl()))
            && (this.getYearM() == null ? other.getYearM() == null : this.getYearM().equals(other.getYearM()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getYoukuId() == null ? other.getYoukuId() == null : this.getYoukuId().equals(other.getYoukuId()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getBrandType() == null ? other.getBrandType() == null : this.getBrandType().equals(other.getBrandType()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getVideoDesc() == null ? other.getVideoDesc() == null : this.getVideoDesc().equals(other.getVideoDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
        result = prime * result + ((getVideoUrl() == null) ? 0 : getVideoUrl().hashCode());
        result = prime * result + ((getYearM() == null) ? 0 : getYearM().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getYoukuId() == null) ? 0 : getYoukuId().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getBrandType() == null) ? 0 : getBrandType().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getVideoDesc() == null) ? 0 : getVideoDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_video_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", picture=").append(picture);
        sb.append(", videoUrl=").append(videoUrl);
        sb.append(", yearM=").append(yearM);
        sb.append(", brandId=").append(brandId);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", youkuId=").append(youkuId);
        sb.append(", flag=").append(flag);
        sb.append(", title=").append(title);
        sb.append(", brandType=").append(brandType);
        sb.append(", category=").append(category);
        sb.append(", videoDesc=").append(videoDesc);
        sb.append("]");
        return sb.toString();
    }
    
    public static enum BrandVideosType{//主题类别
    	
    	BRAND_TVC("tvc"),//品牌
    	BRAND_INDEX("index");//首页

    	BrandVideosType(String value) {
			this.value = value;
		}

		private final String value;

		public String toString() {
			return value;
		}
    }
}