package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /** 
	 *  
	 *  
	 * @param id
	 * @param name
	 * @param parentId
	 * @param isDeleted
	 * @param createTime
	 * @param updateTime
	 * @param seq
	 * @param brandType
	 * @param language
	 * @param title
	 * @param des
	 * @param keywords
	 * @param brief 
	 */ 
	
	public Category(Integer id, String name, Integer parentId,
			String isDeleted, Date createTime, Date updateTime, Integer seq,
			String brandType, String language, String title, String des,
			String keywords, String brief) {
		super();
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.isDeleted = isDeleted;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.seq = seq;
		this.brandType = brandType;
		this.language = language;
		this.title = title;
		this.des = des;
		this.keywords = keywords;
		this.brief = brief;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted = "0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_tbl.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    private String brandType;
    
    private String language;
    private String title;
    private String des;
    private String keywords;
    private String brief;
    
    
    /**
	 * @return title 
	 */
	
	public String getTitle() {
		return title;
	}

	/** 
	 * @param title 要设置的 title 
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return des 
	 */
	
	public String getDes() {
		return des;
	}

	/** 
	 * @param des 要设置的 des 
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * @return keywords 
	 */
	
	public String getKeywords() {
		return keywords;
	}

	/** 
	 * @param keywords 要设置的 keywords 
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * @return brief 
	 */
	
	public String getBrief() {
		return brief;
	}

	/** 
	 * @param brief 要设置的 brief 
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.id
     *
     * @return the value of resource_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.id
     *
     * @param id the value for resource_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.name
     *
     * @return the value of resource_tbl.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.name
     *
     * @param name the value for resource_tbl.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.parent_id
     *
     * @return the value of resource_tbl.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId==null?0:parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.parent_id
     *
     * @param parentId the value for resource_tbl.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.is_deleted
     *
     * @return the value of resource_tbl.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.is_deleted
     *
     * @param isDeleted the value for resource_tbl.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.create_time
     *
     * @return the value of resource_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.create_time
     *
     * @param createTime the value for resource_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.update_time
     *
     * @return the value of resource_tbl.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.update_time
     *
     * @param updateTime the value for resource_tbl.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_tbl.seq
     *
     * @return the value of resource_tbl.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_tbl.seq
     *
     * @param seq the value for resource_tbl.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    
    public String getBrandType() {
		return brandType;
	}

	public void setBrandType(String brandType) {
		this.brandType = brandType == null ? "" : brandType.trim();
	}

	
	
	public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language==null?"":language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Category other = (Category) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getBrandType() == null ? other.getBrandType() == null : this.getBrandType().equals(other.getBrandType()))
            && (this.getLanguage() == null ? other.getLanguage() == null : this.getLanguage().equals(other.getLanguage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getBrandType() == null) ? 0 : getBrandType().hashCode());
        result = prime * result + ((getLanguage() == null) ? 0 : getLanguage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", seq=").append(seq);
        sb.append(", brandType=").append(brandType);
        sb.append(", language=").append(language);
        sb.append("]");
        return sb.toString();
    }
}