package com.cloudeasy.model;

import java.io.Serializable;

public class MovePicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.alt
     *
     * @mbggenerated
     */
    private String alt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.pw
     *
     * @mbggenerated
     */
    private Integer pw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    public MovePicture(Integer id, String path, String url, String alt, Integer pw, String flag) {
        this.id = id;
        this.path = path;
        this.url = url;
        this.alt = alt;
        this.pw = pw;
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    public MovePicture() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.id
     *
     * @return the value of picture_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.id
     *
     * @param id the value for picture_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.path
     *
     * @return the value of picture_tbl.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.path
     *
     * @param path the value for picture_tbl.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.url
     *
     * @return the value of picture_tbl.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.url
     *
     * @param url the value for picture_tbl.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.alt
     *
     * @return the value of picture_tbl.alt
     *
     * @mbggenerated
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.alt
     *
     * @param alt the value for picture_tbl.alt
     *
     * @mbggenerated
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.pw
     *
     * @return the value of picture_tbl.pw
     *
     * @mbggenerated
     */
    public Integer getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.pw
     *
     * @param pw the value for picture_tbl.pw
     *
     * @mbggenerated
     */
    public void setPw(Integer pw) {
        this.pw = pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_tbl.flag
     *
     * @return the value of picture_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_tbl.flag
     *
     * @param flag the value for picture_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MovePicture other = (MovePicture) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getAlt() == null ? other.getAlt() == null : this.getAlt().equals(other.getAlt()))
            && (this.getPw() == null ? other.getPw() == null : this.getPw().equals(other.getPw()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getAlt() == null) ? 0 : getAlt().hashCode());
        result = prime * result + ((getPw() == null) ? 0 : getPw().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", path=").append(path);
        sb.append(", url=").append(url);
        sb.append(", alt=").append(alt);
        sb.append(", pw=").append(pw);
        sb.append(", flag=").append(flag);
        sb.append("]");
        return sb.toString();
    }
}