package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class NewsHonour implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.year_month
     *
     * @mbggenerated
     */
    private Integer yearM;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.month_m
     *
     * @mbggenerated
     */
    private Integer monthM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.news_source
     *
     * @mbggenerated
     */
    private String newsSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.news_author
     *
     * @mbggenerated
     */
    private String newsAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.brief
     *
     * @mbggenerated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.is_check
     *
     * @mbggenerated
     */
    private String isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.checher
     *
     * @mbggenerated
     */
    private String checher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.news_type_id
     *
     * @mbggenerated
     */
    private Integer newsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.check_time
     *
     * @mbggenerated
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_honour_tbl.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    public NewsHonour(Integer id, String title, Integer yearM, Integer monthM, String videoUrl, String picture, String newsSource, String newsAuthor, String brief, String isCheck, String checher, Integer newsTypeId, Date checkTime, Date createTime, String createUser, String flag, String content) {
        this.id = id;
        this.title = title;
        this.yearM = yearM;
        this.monthM = monthM;
        this.videoUrl = videoUrl;
        this.picture = picture;
        this.newsSource = newsSource;
        this.newsAuthor = newsAuthor;
        this.brief = brief;
        this.isCheck = isCheck;
        this.checher = checher;
        this.newsTypeId = newsTypeId;
        this.checkTime = checkTime;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    public NewsHonour() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.id
     *
     * @return the value of news_honour_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.id
     *
     * @param id the value for news_honour_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.title
     *
     * @return the value of news_honour_tbl.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.title
     *
     * @param title the value for news_honour_tbl.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.year_month
     *
     * @return the value of news_honour_tbl.year_month
     *
     * @mbggenerated
     */
    public Integer getYearM() {
        return yearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.year_month
     *
     * @param yearMonth the value for news_honour_tbl.year_month
     *
     * @mbggenerated
     */
    public void setYearM(Integer yearM) {
        this.yearM = yearM;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.year_month
     *
     * @return the value of news_honour_tbl.year_month
     *
     * @mbggenerated
     */
    public Integer getMonthM() {
        return monthM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.year_month
     *
     * @param yearMonth the value for news_honour_tbl.year_month
     *
     * @mbggenerated
     */
    public void setMonthM(Integer monthM) {
        this.monthM = monthM;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.video_url
     *
     * @return the value of news_honour_tbl.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.video_url
     *
     * @param videoUrl the value for news_honour_tbl.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.picture
     *
     * @return the value of news_honour_tbl.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.picture
     *
     * @param picture the value for news_honour_tbl.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.news_source
     *
     * @return the value of news_honour_tbl.news_source
     *
     * @mbggenerated
     */
    public String getNewsSource() {
        return newsSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.news_source
     *
     * @param newsSource the value for news_honour_tbl.news_source
     *
     * @mbggenerated
     */
    public void setNewsSource(String newsSource) {
        this.newsSource = newsSource == null ? null : newsSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.news_author
     *
     * @return the value of news_honour_tbl.news_author
     *
     * @mbggenerated
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.news_author
     *
     * @param newsAuthor the value for news_honour_tbl.news_author
     *
     * @mbggenerated
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor == null ? null : newsAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.brief
     *
     * @return the value of news_honour_tbl.brief
     *
     * @mbggenerated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.brief
     *
     * @param brief the value for news_honour_tbl.brief
     *
     * @mbggenerated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.is_check
     *
     * @return the value of news_honour_tbl.is_check
     *
     * @mbggenerated
     */
    public String getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.is_check
     *
     * @param isCheck the value for news_honour_tbl.is_check
     *
     * @mbggenerated
     */
    public void setIsCheck(String isCheck) {
        this.isCheck = isCheck == null ? null : isCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.checher
     *
     * @return the value of news_honour_tbl.checher
     *
     * @mbggenerated
     */
    public String getChecher() {
        return checher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.checher
     *
     * @param checher the value for news_honour_tbl.checher
     *
     * @mbggenerated
     */
    public void setChecher(String checher) {
        this.checher = checher == null ? null : checher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.news_type_id
     *
     * @return the value of news_honour_tbl.news_type_id
     *
     * @mbggenerated
     */
    public Integer getNewsTypeId() {
        return newsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.news_type_id
     *
     * @param newsTypeId the value for news_honour_tbl.news_type_id
     *
     * @mbggenerated
     */
    public void setNewsTypeId(Integer newsTypeId) {
        this.newsTypeId = newsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.check_time
     *
     * @return the value of news_honour_tbl.check_time
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.check_time
     *
     * @param checkTime the value for news_honour_tbl.check_time
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.create_time
     *
     * @return the value of news_honour_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.create_time
     *
     * @param createTime the value for news_honour_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.create_user
     *
     * @return the value of news_honour_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.create_user
     *
     * @param createUser the value for news_honour_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.flag
     *
     * @return the value of news_honour_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.flag
     *
     * @param flag the value for news_honour_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_honour_tbl.content
     *
     * @return the value of news_honour_tbl.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_honour_tbl.content
     *
     * @param content the value for news_honour_tbl.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NewsHonour other = (NewsHonour) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getYearM() == null ? other.getYearM() == null : this.getYearM().equals(other.getYearM()))
            && (this.getMonthM() == null ? other.getMonthM() == null : this.getMonthM().equals(other.getMonthM()))
            && (this.getVideoUrl() == null ? other.getVideoUrl() == null : this.getVideoUrl().equals(other.getVideoUrl()))
            && (this.getPicture() == null ? other.getPicture() == null : this.getPicture().equals(other.getPicture()))
            && (this.getNewsSource() == null ? other.getNewsSource() == null : this.getNewsSource().equals(other.getNewsSource()))
            && (this.getNewsAuthor() == null ? other.getNewsAuthor() == null : this.getNewsAuthor().equals(other.getNewsAuthor()))
            && (this.getBrief() == null ? other.getBrief() == null : this.getBrief().equals(other.getBrief()))
            && (this.getIsCheck() == null ? other.getIsCheck() == null : this.getIsCheck().equals(other.getIsCheck()))
            && (this.getChecher() == null ? other.getChecher() == null : this.getChecher().equals(other.getChecher()))
            && (this.getNewsTypeId() == null ? other.getNewsTypeId() == null : this.getNewsTypeId().equals(other.getNewsTypeId()))
            && (this.getCheckTime() == null ? other.getCheckTime() == null : this.getCheckTime().equals(other.getCheckTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getYearM() == null) ? 0 : getYearM().hashCode());
        result = prime * result + ((getYearM() == null) ? 0 : getYearM().hashCode());
        result = prime * result + ((getVideoUrl() == null) ? 0 : getVideoUrl().hashCode());
        result = prime * result + ((getPicture() == null) ? 0 : getPicture().hashCode());
        result = prime * result + ((getNewsSource() == null) ? 0 : getNewsSource().hashCode());
        result = prime * result + ((getNewsAuthor() == null) ? 0 : getNewsAuthor().hashCode());
        result = prime * result + ((getBrief() == null) ? 0 : getBrief().hashCode());
        result = prime * result + ((getIsCheck() == null) ? 0 : getIsCheck().hashCode());
        result = prime * result + ((getChecher() == null) ? 0 : getChecher().hashCode());
        result = prime * result + ((getNewsTypeId() == null) ? 0 : getNewsTypeId().hashCode());
        result = prime * result + ((getCheckTime() == null) ? 0 : getCheckTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", yearM=").append(yearM);
        sb.append(", monthM=").append(monthM);
        sb.append(", videoUrl=").append(videoUrl);
        sb.append(", picture=").append(picture);
        sb.append(", newsSource=").append(newsSource);
        sb.append(", newsAuthor=").append(newsAuthor);
        sb.append(", brief=").append(brief);
        sb.append(", isCheck=").append(isCheck);
        sb.append(", checher=").append(checher);
        sb.append(", newsTypeId=").append(newsTypeId);
        sb.append(", checkTime=").append(checkTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}