package com.cloudeasy.model;

import java.util.Date;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.orders_id
     *
     * @mbggenerated
     */
    private Integer ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.partnum
     *
     * @mbggenerated
     */
    private String partnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.lastcreate
     *
     * @mbggenerated
     */
    private Date lastcreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.lastupdate
     *
     * @mbggenerated
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.totalproduct
     *
     * @mbggenerated
     */
    private Double totalproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.quantity
     *
     * @mbggenerated
     */
    private Short quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.taxamount
     *
     * @mbggenerated
     */
    private Double taxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.totaladjustment
     *
     * @mbggenerated
     */
    private Double totaladjustment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail_tbl.shipcharge
     *
     * @mbggenerated
     */
    private Double shipcharge;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_tbl
     *
     * @mbggenerated
     */
    public OrderDetail(Integer id, Integer ordersId, Integer productId, String partnum, Integer userId, Integer addressId, Double price, String status, Date lastcreate, Date lastupdate, Double totalproduct, Short quantity, Double taxamount, Double totaladjustment, Double shipcharge) {
        this.id = id;
        this.ordersId = ordersId;
        this.productId = productId;
        this.partnum = partnum;
        this.userId = userId;
        this.addressId = addressId;
        this.price = price;
        this.status = status;
        this.lastcreate = lastcreate;
        this.lastupdate = lastupdate;
        this.totalproduct = totalproduct;
        this.quantity = quantity;
        this.taxamount = taxamount;
        this.totaladjustment = totaladjustment;
        this.shipcharge = shipcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_tbl
     *
     * @mbggenerated
     */
    public OrderDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.id
     *
     * @return the value of order_detail_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.id
     *
     * @param id the value for order_detail_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.orders_id
     *
     * @return the value of order_detail_tbl.orders_id
     *
     * @mbggenerated
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.orders_id
     *
     * @param ordersId the value for order_detail_tbl.orders_id
     *
     * @mbggenerated
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.product_id
     *
     * @return the value of order_detail_tbl.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.product_id
     *
     * @param productId the value for order_detail_tbl.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.partnum
     *
     * @return the value of order_detail_tbl.partnum
     *
     * @mbggenerated
     */
    public String getPartnum() {
        return partnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.partnum
     *
     * @param partnum the value for order_detail_tbl.partnum
     *
     * @mbggenerated
     */
    public void setPartnum(String partnum) {
        this.partnum = partnum == null ? null : partnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.user_id
     *
     * @return the value of order_detail_tbl.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.user_id
     *
     * @param userId the value for order_detail_tbl.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.address_id
     *
     * @return the value of order_detail_tbl.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.address_id
     *
     * @param addressId the value for order_detail_tbl.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.price
     *
     * @return the value of order_detail_tbl.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.price
     *
     * @param price the value for order_detail_tbl.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.status
     *
     * @return the value of order_detail_tbl.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.status
     *
     * @param status the value for order_detail_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.lastcreate
     *
     * @return the value of order_detail_tbl.lastcreate
     *
     * @mbggenerated
     */
    public Date getLastcreate() {
        return lastcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.lastcreate
     *
     * @param lastcreate the value for order_detail_tbl.lastcreate
     *
     * @mbggenerated
     */
    public void setLastcreate(Date lastcreate) {
        this.lastcreate = lastcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.lastupdate
     *
     * @return the value of order_detail_tbl.lastupdate
     *
     * @mbggenerated
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.lastupdate
     *
     * @param lastupdate the value for order_detail_tbl.lastupdate
     *
     * @mbggenerated
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.totalproduct
     *
     * @return the value of order_detail_tbl.totalproduct
     *
     * @mbggenerated
     */
    public Double getTotalproduct() {
        return totalproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.totalproduct
     *
     * @param totalproduct the value for order_detail_tbl.totalproduct
     *
     * @mbggenerated
     */
    public void setTotalproduct(Double totalproduct) {
        this.totalproduct = totalproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.quantity
     *
     * @return the value of order_detail_tbl.quantity
     *
     * @mbggenerated
     */
    public Short getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.quantity
     *
     * @param quantity the value for order_detail_tbl.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.taxamount
     *
     * @return the value of order_detail_tbl.taxamount
     *
     * @mbggenerated
     */
    public Double getTaxamount() {
        return taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.taxamount
     *
     * @param taxamount the value for order_detail_tbl.taxamount
     *
     * @mbggenerated
     */
    public void setTaxamount(Double taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.totaladjustment
     *
     * @return the value of order_detail_tbl.totaladjustment
     *
     * @mbggenerated
     */
    public Double getTotaladjustment() {
        return totaladjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.totaladjustment
     *
     * @param totaladjustment the value for order_detail_tbl.totaladjustment
     *
     * @mbggenerated
     */
    public void setTotaladjustment(Double totaladjustment) {
        this.totaladjustment = totaladjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail_tbl.shipcharge
     *
     * @return the value of order_detail_tbl.shipcharge
     *
     * @mbggenerated
     */
    public Double getShipcharge() {
        return shipcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail_tbl.shipcharge
     *
     * @param shipcharge the value for order_detail_tbl.shipcharge
     *
     * @mbggenerated
     */
    public void setShipcharge(Double shipcharge) {
        this.shipcharge = shipcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderDetail other = (OrderDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrdersId() == null ? other.getOrdersId() == null : this.getOrdersId().equals(other.getOrdersId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getPartnum() == null ? other.getPartnum() == null : this.getPartnum().equals(other.getPartnum()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastcreate() == null ? other.getLastcreate() == null : this.getLastcreate().equals(other.getLastcreate()))
            && (this.getLastupdate() == null ? other.getLastupdate() == null : this.getLastupdate().equals(other.getLastupdate()))
            && (this.getTotalproduct() == null ? other.getTotalproduct() == null : this.getTotalproduct().equals(other.getTotalproduct()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getTaxamount() == null ? other.getTaxamount() == null : this.getTaxamount().equals(other.getTaxamount()))
            && (this.getTotaladjustment() == null ? other.getTotaladjustment() == null : this.getTotaladjustment().equals(other.getTotaladjustment()))
            && (this.getShipcharge() == null ? other.getShipcharge() == null : this.getShipcharge().equals(other.getShipcharge()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrdersId() == null) ? 0 : getOrdersId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getPartnum() == null) ? 0 : getPartnum().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastcreate() == null) ? 0 : getLastcreate().hashCode());
        result = prime * result + ((getLastupdate() == null) ? 0 : getLastupdate().hashCode());
        result = prime * result + ((getTotalproduct() == null) ? 0 : getTotalproduct().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getTaxamount() == null) ? 0 : getTaxamount().hashCode());
        result = prime * result + ((getTotaladjustment() == null) ? 0 : getTotaladjustment().hashCode());
        result = prime * result + ((getShipcharge() == null) ? 0 : getShipcharge().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ordersId=").append(ordersId);
        sb.append(", productId=").append(productId);
        sb.append(", partnum=").append(partnum);
        sb.append(", userId=").append(userId);
        sb.append(", addressId=").append(addressId);
        sb.append(", price=").append(price);
        sb.append(", status=").append(status);
        sb.append(", lastcreate=").append(lastcreate);
        sb.append(", lastupdate=").append(lastupdate);
        sb.append(", totalproduct=").append(totalproduct);
        sb.append(", quantity=").append(quantity);
        sb.append(", taxamount=").append(taxamount);
        sb.append(", totaladjustment=").append(totaladjustment);
        sb.append(", shipcharge=").append(shipcharge);
        sb.append("]");
        return sb.toString();
    }
}