package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.pic_src
     *
     * @mbggenerated
     */
    private String picSrc;
    
    
    private String shortDesc;//产品简介

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.product_desc
     *
     * @mbggenerated
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.table_relate_flag
     *
     * @mbggenerated
     */
    private String tableRelateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.table_id
     *
     * @mbggenerated
     */
    private String tableId;//brandType

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.pw
     *
     * @mbggenerated
     */
    private Integer pw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.taobao_url
     *
     * @mbggenerated
     */
    private String taobaoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteKey1
     *
     * @mbggenerated
     */
    private String noteKey1;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteValue1
     *
     * @mbggenerated
     */
    private String noteValue1;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteKey2
     *
     * @mbggenerated
     */
    private String noteKey2;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteValue2
     *
     * @mbggenerated
     */
    private String noteValue2;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteKey3
     *
     * @mbggenerated
     */
    private String noteKey3;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteValue3
     *
     * @mbggenerated
     */
    private String noteValue3;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteKey4
     *
     * @mbggenerated
     */
    private String noteKey4;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteValue4
     *
     * @mbggenerated
     */
    private String noteValue4;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteDesc1
     *
     * @mbggenerated
     */
    private String noteDesc1;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteDesc2
     *
     * @mbggenerated
     */
    private String noteDesc2;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteDesc3
     *
     * @mbggenerated
     */
    private String noteDesc3;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.noteDesc4
     *
     * @mbggenerated
     */
    private String noteDesc4;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_tbl.mainProductId
     *
     * @mbggenerated
     */
    private Integer mainProductId;
    
    private String language;
    
    private String tags;
    
    


    /**
	 * @return tags 
	 */
	
	public String getTags() {
		return tags;
	}

	/** 
	 * @param tags 要设置的 tags 
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}

	public Integer getMainProductId() {
		return mainProductId;
	}

	public void setMainProductId(Integer mainProductId) {
		this.mainProductId = mainProductId;
	}
	
	public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getNoteDesc1() {
		return noteDesc1;
	}

	public void setNoteDesc1(String noteDesc1) {
		this.noteDesc1 = noteDesc1;
	}

	public String getNoteDesc2() {
		return noteDesc2;
	}

	public void setNoteDesc2(String noteDesc2) {
		this.noteDesc2 = noteDesc2;
	}

	public String getNoteDesc3() {
		return noteDesc3;
	}

	public void setNoteDesc3(String noteDesc3) {
		this.noteDesc3 = noteDesc3;
	}

	public String getNoteDesc4() {
		return noteDesc4;
	}

	public void setNoteDesc4(String noteDesc4) {
		this.noteDesc4 = noteDesc4;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    public Product(Integer id, String productName, String picSrc, String productDesc, 
    		String tableRelateFlag, String tableId, Integer pw, Date createTime, 
    		String createUser, String flag, String taobaoUrl,String shortDesc, 
    		String noteKey1, String noteValue1,String noteKey2, String noteValue2,
    		String noteKey3, String noteValue3,String noteKey4, String noteValue4,
    		String noteDesc1, String noteDesc2,String noteDesc3, String noteDesc4,
    		Integer mainProductId,String language) {
        this.id = id;
        this.productName = productName;
        this.picSrc = picSrc;
        this.productDesc = productDesc;
        this.tableRelateFlag = tableRelateFlag;
        this.tableId = tableId;
        this.pw = pw;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.taobaoUrl = taobaoUrl;
        this.shortDesc = shortDesc;
        this.noteKey1 = noteKey1;
        this.noteValue1 = noteValue1;
        this.noteKey2 = noteKey2;
        this.noteValue2 = noteValue2;
        this.noteKey3 = noteKey3;
        this.noteValue3 = noteValue3;
        this.noteKey4 = noteKey4;
        this.noteValue4 = noteValue4;
        this.noteDesc1 = noteDesc1;
        this.noteDesc2 = noteDesc2;
        this.noteDesc3 = noteDesc3;
        this.noteDesc4 = noteDesc4;
        this.mainProductId = mainProductId;
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.id
     *
     * @return the value of product_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.id
     *
     * @param id the value for product_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.product_name
     *
     * @return the value of product_tbl.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.product_name
     *
     * @param productName the value for product_tbl.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.pic_src
     *
     * @return the value of product_tbl.pic_src
     *
     * @mbggenerated
     */
    public String getPicSrc() {
        return picSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.pic_src
     *
     * @param picSrc the value for product_tbl.pic_src
     *
     * @mbggenerated
     */
    public void setPicSrc(String picSrc) {
        this.picSrc = picSrc == null ? null : picSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.product_desc
     *
     * @return the value of product_tbl.product_desc
     *
     * @mbggenerated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.product_desc
     *
     * @param productDesc the value for product_tbl.product_desc
     *
     * @mbggenerated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }
    
    public String getShortDesc() {
		return shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc == null ? null : shortDesc.trim();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.table_relate_flag
     *
     * @return the value of product_tbl.table_relate_flag
     *
     * @mbggenerated
     */
    public String getTableRelateFlag() {
        return tableRelateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.table_relate_flag
     *
     * @param tableRelateFlag the value for product_tbl.table_relate_flag
     *
     * @mbggenerated
     */
    public void setTableRelateFlag(String tableRelateFlag) {
        this.tableRelateFlag = tableRelateFlag == null ? null : tableRelateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.table_id
     *
     * @return the value of product_tbl.table_id
     *
     * @mbggenerated
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.table_id
     *
     * @param tableId the value for product_tbl.table_id
     *
     * @mbggenerated
     */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.pw
     *
     * @return the value of product_tbl.pw
     *
     * @mbggenerated
     */
    public Integer getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.pw
     *
     * @param pw the value for product_tbl.pw
     *
     * @mbggenerated
     */
    public void setPw(Integer pw) {
        this.pw = pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.create_time
     *
     * @return the value of product_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.create_time
     *
     * @param createTime the value for product_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.create_user
     *
     * @return the value of product_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.create_user
     *
     * @param createUser the value for product_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.flag
     *
     * @return the value of product_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.flag
     *
     * @param flag the value for product_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_tbl.taobao_url
     *
     * @return the value of product_tbl.taobao_url
     *
     * @mbggenerated
     */
    public String getTaobaoUrl() {
        return taobaoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_tbl.taobao_url
     *
     * @param taobaoUrl the value for product_tbl.taobao_url
     *
     * @mbggenerated
     */
    public void setTaobaoUrl(String taobaoUrl) {
        this.taobaoUrl = taobaoUrl == null ? null : taobaoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getPicSrc() == null ? other.getPicSrc() == null : this.getPicSrc().equals(other.getPicSrc()))
            && (this.getProductDesc() == null ? other.getProductDesc() == null : this.getProductDesc().equals(other.getProductDesc()))
            && (this.getTableRelateFlag() == null ? other.getTableRelateFlag() == null : this.getTableRelateFlag().equals(other.getTableRelateFlag()))
            && (this.getTableId() == null ? other.getTableId() == null : this.getTableId().equals(other.getTableId()))
            && (this.getPw() == null ? other.getPw() == null : this.getPw().equals(other.getPw()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getTaobaoUrl() == null ? other.getTaobaoUrl() == null : this.getTaobaoUrl().equals(other.getTaobaoUrl()))
            && (this.getShortDesc() == null ? other.getShortDesc() == null : this.getShortDesc().equals(other.getShortDesc()))
            && (this.getNoteKey1() == null ? other.getNoteKey1() == null : this.getNoteKey1().equals(other.getNoteKey1()))
            && (this.getNoteValue1() == null ? other.getNoteValue1() == null : this.getNoteValue1().equals(other.getNoteValue1()))
            && (this.getNoteKey2() == null ? other.getNoteKey2() == null : this.getNoteKey2().equals(other.getNoteKey2()))
            && (this.getNoteValue2() == null ? other.getNoteValue2() == null : this.getNoteValue2().equals(other.getNoteValue2()))
            && (this.getNoteKey3() == null ? other.getNoteKey3() == null : this.getNoteKey3().equals(other.getNoteKey3()))
            && (this.getNoteValue3() == null ? other.getNoteValue3() == null : this.getNoteValue3().equals(other.getNoteValue3()))
            && (this.getNoteKey4() == null ? other.getNoteKey4() == null : this.getNoteKey4().equals(other.getNoteKey4()))
            && (this.getNoteValue4() == null ? other.getNoteValue4() == null : this.getNoteValue4().equals(other.getNoteValue4()))
            && (this.getNoteDesc1() == null ? other.getNoteDesc1() == null : this.getNoteDesc1().equals(other.getNoteDesc1()))
            && (this.getNoteDesc2() == null ? other.getNoteDesc2() == null : this.getNoteDesc2().equals(other.getNoteDesc2()))
            && (this.getNoteDesc3() == null ? other.getNoteDesc3() == null : this.getNoteDesc3().equals(other.getNoteDesc3()))
            && (this.getNoteDesc4() == null ? other.getNoteDesc4() == null : this.getNoteDesc4().equals(other.getNoteDesc4()))
            && (this.getMainProductId() == null ? other.getMainProductId() == null : this.getMainProductId().equals(other.getMainProductId()))
            && (this.getLanguage() == null ? other.getLanguage() == null : this.getLanguage().equals(other.getLanguage()));
    }

    public String getNoteKey1() {
		return noteKey1;
	}

	public void setNoteKey1(String noteKey1) {
		this.noteKey1 = noteKey1;
	}

	public String getNoteValue1() {
		return noteValue1;
	}

	public void setNoteValue1(String noteValue1) {
		this.noteValue1 = noteValue1;
	}

	public String getNoteKey2() {
		return noteKey2;
	}

	public void setNoteKey2(String noteKey2) {
		this.noteKey2 = noteKey2;
	}

	public String getNoteValue2() {
		return noteValue2;
	}

	public void setNoteValue2(String noteValue2) {
		this.noteValue2 = noteValue2;
	}

	public String getNoteKey3() {
		return noteKey3;
	}

	public void setNoteKey3(String noteKey3) {
		this.noteKey3 = noteKey3;
	}

	public String getNoteValue3() {
		return noteValue3;
	}

	public void setNoteValue3(String noteValue3) {
		this.noteValue3 = noteValue3;
	}

	public String getNoteKey4() {
		return noteKey4;
	}

	public void setNoteKey4(String noteKey4) {
		this.noteKey4 = noteKey4;
	}

	public String getNoteValue4() {
		return noteValue4;
	}

	public void setNoteValue4(String noteValue4) {
		this.noteValue4 = noteValue4;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getPicSrc() == null) ? 0 : getPicSrc().hashCode());
        result = prime * result + ((getProductDesc() == null) ? 0 : getProductDesc().hashCode());
        result = prime * result + ((getTableRelateFlag() == null) ? 0 : getTableRelateFlag().hashCode());
        result = prime * result + ((getTableId() == null) ? 0 : getTableId().hashCode());
        result = prime * result + ((getPw() == null) ? 0 : getPw().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getTaobaoUrl() == null) ? 0 : getTaobaoUrl().hashCode());
        result = prime * result + ((getShortDesc() == null) ? 0 : getShortDesc().hashCode());
        result = prime * result + ((getNoteKey1() == null) ? 0 : getNoteKey1().hashCode());
        result = prime * result + ((getNoteValue1() == null) ? 0 : getNoteValue1().hashCode());
        result = prime * result + ((getNoteKey2() == null) ? 0 : getNoteKey2().hashCode());
        result = prime * result + ((getNoteValue2() == null) ? 0 : getNoteValue2().hashCode());
        result = prime * result + ((getNoteKey3() == null) ? 0 : getNoteKey3().hashCode());
        result = prime * result + ((getNoteValue3() == null) ? 0 : getNoteValue3().hashCode());
        result = prime * result + ((getNoteKey4() == null) ? 0 : getNoteKey4().hashCode());
        result = prime * result + ((getNoteValue4() == null) ? 0 : getNoteValue4().hashCode());
        result = prime * result + ((getNoteDesc1() == null) ? 0 : getNoteDesc1().hashCode());
        result = prime * result + ((getNoteDesc2() == null) ? 0 : getNoteDesc2().hashCode());
        result = prime * result + ((getNoteDesc3() == null) ? 0 : getNoteDesc3().hashCode());
        result = prime * result + ((getNoteDesc4() == null) ? 0 : getNoteDesc4().hashCode());
        result = prime * result + ((getMainProductId() == null) ? 0 : getMainProductId().hashCode());
        result = prime * result + ((getLanguage() == null) ? 0 : getLanguage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productName=").append(productName);
        sb.append(", picSrc=").append(picSrc);
        sb.append(", productDesc=").append(productDesc);
        sb.append(", tableRelateFlag=").append(tableRelateFlag);
        sb.append(", tableId=").append(tableId);
        sb.append(", pw=").append(pw);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", taobaoUrl=").append(taobaoUrl);
        sb.append(", shortDesc=").append(shortDesc);
        sb.append(", noteKey1=").append(noteKey1);
        sb.append(", noteValue1=").append(noteValue1);
        sb.append(", noteKey2=").append(noteKey2);
        sb.append(", noteValue2=").append(noteValue2);
        sb.append(", noteKey3=").append(noteKey3);
        sb.append(", noteValue3=").append(noteValue3);
        sb.append(", noteKey4=").append(noteKey4);
        sb.append(", noteValue4=").append(noteValue4);
        sb.append(", noteDesc1=").append(noteDesc1);
        sb.append(", noteDesc2=").append(noteDesc2);
        sb.append(", noteDesc3=").append(noteDesc3);
        sb.append(", noteDesc4=").append(noteDesc4);
        sb.append(", mainProductId=").append(mainProductId);
        sb.append(", language=").append(language);
        sb.append("]");
        return sb.toString();
    }
}