package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class Reservation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.fullname
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.mdia
     *
     * @mbggenerated
     */
    private String mdia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.postion
     *
     * @mbggenerated
     */
    private String postion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.interested_area
     *
     * @mbggenerated
     */
    private String interestedArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.outline
     *
     * @mbggenerated
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation_tbl.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    public Reservation(Integer id, String fullname, String mdia, String postion, String email, String telephone, String mobile, String interestedArea, String outline, Date createTime, String createUser, String flag, String status) {
        this.id = id;
        this.fullname = fullname;
        this.mdia = mdia;
        this.postion = postion;
        this.email = email;
        this.telephone = telephone;
        this.mobile = mobile;
        this.interestedArea = interestedArea;
        this.outline = outline;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    public Reservation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.id
     *
     * @return the value of reservation_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.id
     *
     * @param id the value for reservation_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.fullname
     *
     * @return the value of reservation_tbl.fullname
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.fullname
     *
     * @param fullname the value for reservation_tbl.fullname
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.mdia
     *
     * @return the value of reservation_tbl.mdia
     *
     * @mbggenerated
     */
    public String getMdia() {
        return mdia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.mdia
     *
     * @param mdia the value for reservation_tbl.mdia
     *
     * @mbggenerated
     */
    public void setMdia(String mdia) {
        this.mdia = mdia == null ? null : mdia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.postion
     *
     * @return the value of reservation_tbl.postion
     *
     * @mbggenerated
     */
    public String getPostion() {
        return postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.postion
     *
     * @param postion the value for reservation_tbl.postion
     *
     * @mbggenerated
     */
    public void setPostion(String postion) {
        this.postion = postion == null ? null : postion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.email
     *
     * @return the value of reservation_tbl.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.email
     *
     * @param email the value for reservation_tbl.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.telephone
     *
     * @return the value of reservation_tbl.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.telephone
     *
     * @param telephone the value for reservation_tbl.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.mobile
     *
     * @return the value of reservation_tbl.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.mobile
     *
     * @param mobile the value for reservation_tbl.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.interested_area
     *
     * @return the value of reservation_tbl.interested_area
     *
     * @mbggenerated
     */
    public String getInterestedArea() {
        return interestedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.interested_area
     *
     * @param interestedArea the value for reservation_tbl.interested_area
     *
     * @mbggenerated
     */
    public void setInterestedArea(String interestedArea) {
        this.interestedArea = interestedArea == null ? null : interestedArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.outline
     *
     * @return the value of reservation_tbl.outline
     *
     * @mbggenerated
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.outline
     *
     * @param outline the value for reservation_tbl.outline
     *
     * @mbggenerated
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.create_time
     *
     * @return the value of reservation_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.create_time
     *
     * @param createTime the value for reservation_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.create_user
     *
     * @return the value of reservation_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.create_user
     *
     * @param createUser the value for reservation_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.flag
     *
     * @return the value of reservation_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.flag
     *
     * @param flag the value for reservation_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation_tbl.status
     *
     * @return the value of reservation_tbl.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation_tbl.status
     *
     * @param status the value for reservation_tbl.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reservation other = (Reservation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFullname() == null ? other.getFullname() == null : this.getFullname().equals(other.getFullname()))
            && (this.getMdia() == null ? other.getMdia() == null : this.getMdia().equals(other.getMdia()))
            && (this.getPostion() == null ? other.getPostion() == null : this.getPostion().equals(other.getPostion()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getInterestedArea() == null ? other.getInterestedArea() == null : this.getInterestedArea().equals(other.getInterestedArea()))
            && (this.getOutline() == null ? other.getOutline() == null : this.getOutline().equals(other.getOutline()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFullname() == null) ? 0 : getFullname().hashCode());
        result = prime * result + ((getMdia() == null) ? 0 : getMdia().hashCode());
        result = prime * result + ((getPostion() == null) ? 0 : getPostion().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getInterestedArea() == null) ? 0 : getInterestedArea().hashCode());
        result = prime * result + ((getOutline() == null) ? 0 : getOutline().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fullname=").append(fullname);
        sb.append(", mdia=").append(mdia);
        sb.append(", postion=").append(postion);
        sb.append(", email=").append(email);
        sb.append(", telephone=").append(telephone);
        sb.append(", mobile=").append(mobile);
        sb.append(", interestedArea=").append(interestedArea);
        sb.append(", outline=").append(outline);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}