package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class SubBrand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.sub_brand_desc
     *
     * @mbggenerated
     */
    private String subBrandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.pic_src
     *
     * @mbggenerated
     */
    private String picSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    private String weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    public SubBrand(Integer id, String brand, Integer brandId, String subBrandDesc, String picSrc, String url, Date createTime, String createUser, String flag, String weiboId) {
        this.id = id;
        this.brand = brand;
        this.brandId = brandId;
        this.subBrandDesc = subBrandDesc;
        this.picSrc = picSrc;
        this.url = url;
        this.createTime = createTime;
        this.createUser = createUser;
        this.flag = flag;
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    public SubBrand() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.id
     *
     * @return the value of sub_brand_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.id
     *
     * @param id the value for sub_brand_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.brand
     *
     * @return the value of sub_brand_tbl.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.brand
     *
     * @param brand the value for sub_brand_tbl.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.brand_id
     *
     * @return the value of sub_brand_tbl.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.brand_id
     *
     * @param brandId the value for sub_brand_tbl.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.sub_brand_desc
     *
     * @return the value of sub_brand_tbl.sub_brand_desc
     *
     * @mbggenerated
     */
    public String getSubBrandDesc() {
        return subBrandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.sub_brand_desc
     *
     * @param subBrandDesc the value for sub_brand_tbl.sub_brand_desc
     *
     * @mbggenerated
     */
    public void setSubBrandDesc(String subBrandDesc) {
        this.subBrandDesc = subBrandDesc == null ? null : subBrandDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.pic_src
     *
     * @return the value of sub_brand_tbl.pic_src
     *
     * @mbggenerated
     */
    public String getPicSrc() {
        return picSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.pic_src
     *
     * @param picSrc the value for sub_brand_tbl.pic_src
     *
     * @mbggenerated
     */
    public void setPicSrc(String picSrc) {
        this.picSrc = picSrc == null ? null : picSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.url
     *
     * @return the value of sub_brand_tbl.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.url
     *
     * @param url the value for sub_brand_tbl.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.create_time
     *
     * @return the value of sub_brand_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.create_time
     *
     * @param createTime the value for sub_brand_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.create_user
     *
     * @return the value of sub_brand_tbl.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.create_user
     *
     * @param createUser the value for sub_brand_tbl.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.flag
     *
     * @return the value of sub_brand_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.flag
     *
     * @param flag the value for sub_brand_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_brand_tbl.weibo_id
     *
     * @return the value of sub_brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    public String getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_brand_tbl.weibo_id
     *
     * @param weiboId the value for sub_brand_tbl.weibo_id
     *
     * @mbggenerated
     */
    public void setWeiboId(String weiboId) {
        this.weiboId = weiboId == null ? null : weiboId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SubBrand other = (SubBrand) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getSubBrandDesc() == null ? other.getSubBrandDesc() == null : this.getSubBrandDesc().equals(other.getSubBrandDesc()))
            && (this.getPicSrc() == null ? other.getPicSrc() == null : this.getPicSrc().equals(other.getPicSrc()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getWeiboId() == null ? other.getWeiboId() == null : this.getWeiboId().equals(other.getWeiboId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getSubBrandDesc() == null) ? 0 : getSubBrandDesc().hashCode());
        result = prime * result + ((getPicSrc() == null) ? 0 : getPicSrc().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getWeiboId() == null) ? 0 : getWeiboId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", brand=").append(brand);
        sb.append(", brandId=").append(brandId);
        sb.append(", subBrandDesc=").append(subBrandDesc);
        sb.append(", picSrc=").append(picSrc);
        sb.append(", url=").append(url);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", flag=").append(flag);
        sb.append(", weiboId=").append(weiboId);
        sb.append("]");
        return sb.toString();
    }
}