package com.cloudeasy.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.type
     *
     * @mbggenerated
     */
    private Integer type;//0：超级管理员;1:普通用户

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.last_time
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.the_time
     *
     * @mbggenerated
     */
    private Date theTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.last_ip
     *
     * @mbggenerated
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.the_ip
     *
     * @mbggenerated
     */
    private String theIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.is_freeze
     *
     * @mbggenerated
     */
    private String isFreeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.create_user_id
     *
     * @mbggenerated
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.create_type
     *
     * @mbggenerated
     */
    private Integer createType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.enabled
     *
     * @mbggenerated
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.flag
     *
     * @mbggenerated
     */
    private String flag;
    
    private String province;
    
    private String address;
    
    private Integer age;
    
    private String win;
    
    private String company;
    
    private String shortCompany;
    
    private String validateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public User(Integer id, Integer roleId, String username, String password, 
    		Integer type, String mobilePhone, String telephone, String email, 
    		String fax, String memo, Date lastTime, Date theTime, String lastIp, String theIp, 
    		String isFreeze, Integer isDelete, Date createTime, Integer createUserId, Integer createType, 
    		Date updateTime, String realname, String enabled, String salt, String flag,String company,String shortCompany) {
        this.id = id;
        this.roleId = roleId;
        this.username = username;
        this.password = password;
        this.type = type;
        this.mobilePhone = mobilePhone;
        this.telephone = telephone;
        this.email = email;
        this.fax = fax;
        this.memo = memo;
        this.lastTime = lastTime;
        this.theTime = theTime;
        this.lastIp = lastIp;
        this.theIp = theIp;
        this.isFreeze = isFreeze;
        this.isDelete = isDelete;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.createType = createType;
        this.updateTime = updateTime;
        this.realname = realname;
        this.enabled = enabled;
        this.salt = salt;
        this.flag = flag;
        this.company = company;
        this.shortCompany = shortCompany;
    }
    
    public User(Integer id, Integer roleId, String username, String password, 
    		Integer type, String mobilePhone, String telephone, String email, 
    		String fax, String memo, Date lastTime, Date theTime, String lastIp, String theIp, 
    		String isFreeze, Integer isDelete, Date createTime, Integer createUserId, Integer createType, 
    		Date updateTime, String realname, String enabled, String salt, String flag,
    		String province,String address,Integer age,String win,String company,String shortCompany) {
        this.id = id;
        this.roleId = roleId;
        this.username = username;
        this.password = password;
        this.type = type;
        this.mobilePhone = mobilePhone;
        this.telephone = telephone;
        this.email = email;
        this.fax = fax;
        this.memo = memo;
        this.lastTime = lastTime;
        this.theTime = theTime;
        this.lastIp = lastIp;
        this.theIp = theIp;
        this.isFreeze = isFreeze;
        this.isDelete = isDelete;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.createType = createType;
        this.updateTime = updateTime;
        this.realname = realname;
        this.enabled = enabled;
        this.salt = salt;
        this.flag = flag;
        this.province = province;
        this.address = address;
        this.age = age;
        this.win = win;
        this.company = company;
        this.shortCompany = shortCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.id
     *
     * @return the value of user_tbl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.id
     *
     * @param id the value for user_tbl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.role_id
     *
     * @return the value of user_tbl.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.role_id
     *
     * @param roleId the value for user_tbl.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.username
     *
     * @return the value of user_tbl.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.username
     *
     * @param username the value for user_tbl.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.password
     *
     * @return the value of user_tbl.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.password
     *
     * @param password the value for user_tbl.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.type
     *
     * @return the value of user_tbl.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.type
     *
     * @param type the value for user_tbl.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.mobile_phone
     *
     * @return the value of user_tbl.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.mobile_phone
     *
     * @param mobilePhone the value for user_tbl.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.telephone
     *
     * @return the value of user_tbl.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.telephone
     *
     * @param telephone the value for user_tbl.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.email
     *
     * @return the value of user_tbl.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.email
     *
     * @param email the value for user_tbl.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.fax
     *
     * @return the value of user_tbl.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.fax
     *
     * @param fax the value for user_tbl.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.memo
     *
     * @return the value of user_tbl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.memo
     *
     * @param memo the value for user_tbl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.last_time
     *
     * @return the value of user_tbl.last_time
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.last_time
     *
     * @param lastTime the value for user_tbl.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.the_time
     *
     * @return the value of user_tbl.the_time
     *
     * @mbggenerated
     */
    public Date getTheTime() {
        return theTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.the_time
     *
     * @param theTime the value for user_tbl.the_time
     *
     * @mbggenerated
     */
    public void setTheTime(Date theTime) {
        this.theTime = theTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.last_ip
     *
     * @return the value of user_tbl.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.last_ip
     *
     * @param lastIp the value for user_tbl.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.the_ip
     *
     * @return the value of user_tbl.the_ip
     *
     * @mbggenerated
     */
    public String getTheIp() {
        return theIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.the_ip
     *
     * @param theIp the value for user_tbl.the_ip
     *
     * @mbggenerated
     */
    public void setTheIp(String theIp) {
        this.theIp = theIp == null ? null : theIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.is_freeze
     *
     * @return the value of user_tbl.is_freeze
     *
     * @mbggenerated
     */
    public String getIsFreeze() {
        return isFreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.is_freeze
     *
     * @param isFreeze the value for user_tbl.is_freeze
     *
     * @mbggenerated
     */
    public void setIsFreeze(String isFreeze) {
        this.isFreeze = isFreeze == null ? null : isFreeze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.is_delete
     *
     * @return the value of user_tbl.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.is_delete
     *
     * @param isDelete the value for user_tbl.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.create_time
     *
     * @return the value of user_tbl.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.create_time
     *
     * @param createTime the value for user_tbl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.create_user_id
     *
     * @return the value of user_tbl.create_user_id
     *
     * @mbggenerated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.create_user_id
     *
     * @param createUserId the value for user_tbl.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.create_type
     *
     * @return the value of user_tbl.create_type
     *
     * @mbggenerated
     */
    public Integer getCreateType() {
        return createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.create_type
     *
     * @param createType the value for user_tbl.create_type
     *
     * @mbggenerated
     */
    public void setCreateType(Integer createType) {
        this.createType = createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.update_time
     *
     * @return the value of user_tbl.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.update_time
     *
     * @param updateTime the value for user_tbl.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.realname
     *
     * @return the value of user_tbl.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.realname
     *
     * @param realname the value for user_tbl.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.enabled
     *
     * @return the value of user_tbl.enabled
     *
     * @mbggenerated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.enabled
     *
     * @param enabled the value for user_tbl.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.salt
     *
     * @return the value of user_tbl.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.salt
     *
     * @param salt the value for user_tbl.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.flag
     *
     * @return the value of user_tbl.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.flag
     *
     * @param flag the value for user_tbl.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province==null?"":province.trim();
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address==null?"":address.trim();
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getWin() {
		return win;
	}

	public void setWin(String win) {
		this.win = win;
	}
	
	public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getShortCompany() {
        return shortCompany;
    }

    public void setShortCompany(String shortCompany) {
        this.shortCompany = shortCompany;
    }
    
    

    public String getValidateCode() {
        return validateCode;
    }

    public void setValidateCode(String validateCode) {
        this.validateCode = validateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getMobilePhone() == null ? other.getMobilePhone() == null : this.getMobilePhone().equals(other.getMobilePhone()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getLastTime() == null ? other.getLastTime() == null : this.getLastTime().equals(other.getLastTime()))
            && (this.getTheTime() == null ? other.getTheTime() == null : this.getTheTime().equals(other.getTheTime()))
            && (this.getLastIp() == null ? other.getLastIp() == null : this.getLastIp().equals(other.getLastIp()))
            && (this.getTheIp() == null ? other.getTheIp() == null : this.getTheIp().equals(other.getTheIp()))
            && (this.getIsFreeze() == null ? other.getIsFreeze() == null : this.getIsFreeze().equals(other.getIsFreeze()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateType() == null ? other.getCreateType() == null : this.getCreateType().equals(other.getCreateType()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRealname() == null ? other.getRealname() == null : this.getRealname().equals(other.getRealname()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
        	&& (this.getWin() == null ? other.getWin() == null : this.getWin().equals(other.getWin()))
        	&& (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getShortCompany() == null ? other.getShortCompany() == null : this.getShortCompany().equals(other.getShortCompany()))
            && (this.getValidateCode() == null ? other.getValidateCode() == null : this.getValidateCode().equals(other.getValidateCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getMobilePhone() == null) ? 0 : getMobilePhone().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getLastTime() == null) ? 0 : getLastTime().hashCode());
        result = prime * result + ((getTheTime() == null) ? 0 : getTheTime().hashCode());
        result = prime * result + ((getLastIp() == null) ? 0 : getLastIp().hashCode());
        result = prime * result + ((getTheIp() == null) ? 0 : getTheIp().hashCode());
        result = prime * result + ((getIsFreeze() == null) ? 0 : getIsFreeze().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateType() == null) ? 0 : getCreateType().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRealname() == null) ? 0 : getRealname().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getWin() == null) ? 0 : getWin().hashCode());
        
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getShortCompany() == null) ? 0 : getShortCompany().hashCode());
        result = prime * result + ((getValidateCode() == null) ? 0 : getValidateCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", type=").append(type);
        sb.append(", mobilePhone=").append(mobilePhone);
        sb.append(", telephone=").append(telephone);
        sb.append(", email=").append(email);
        sb.append(", fax=").append(fax);
        sb.append(", memo=").append(memo);
        sb.append(", lastTime=").append(lastTime);
        sb.append(", theTime=").append(theTime);
        sb.append(", lastIp=").append(lastIp);
        sb.append(", theIp=").append(theIp);
        sb.append(", isFreeze=").append(isFreeze);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createType=").append(createType);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", realname=").append(realname);
        sb.append(", enabled=").append(enabled);
        sb.append(", salt=").append(salt);
        sb.append(", flag=").append(flag);
        sb.append(", province=").append(province);
        sb.append(", address=").append(address);
        sb.append(", age=").append(age);
        sb.append(", win=").append(win);
        sb.append(", company=").append(company);
        sb.append(", shortCompany=").append(shortCompany);
        sb.append(", validateCode=").append(validateCode);
        sb.append("]");
        return sb.toString();
    }
}