package com.cloudeasy.dao;

import java.util.List;
import java.util.Map;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.AboutArticle;

public interface AboutArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int insert(AboutArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int insertSelective(AboutArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    AboutArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AboutArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AboutArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_article_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AboutArticle record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);
    
    List<AboutArticle> queryForList(AboutArticle record);
}