package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.Attribute;
import com.cloudeasy.model.Brand;

public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    int insert(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    Attribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attribute record);
    
    /**
     * 名称是否存在
     * @param model
     * @return
     */
    public int isName(BaseDTO model);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);

    
	List<Attribute> queryByList(BaseDTO model);

	
	/**
	 * 获取所有商品属性
	 * @param model
	 * @return
	 */
	List<Attribute> findAllAttribute(BaseDTO model);
}