package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.common.DataGridModel;
import com.cloudeasy.model.Category;
import com.cloudeasy.mybatis.DynamicDBValues;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);
    
    List<Category> findAllCategorys(DynamicDBValues dy);
    
    int queryByCount(Category res);
    
    List<Category> queryByList(DataGridModel model);
    
    List<Category> queryResByParentId(Category category);
}