package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.Download;
import com.cloudeasy.mybatis.DynamicDBValues;

public interface DownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    int insert(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    Download selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Download record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int queryByCount(BaseDTO model);
    /**
     * 获取所有风采
     * @param flag
     * @return list
     */
    List<Download> queryForList(BaseDTO model);
    
	public Integer queryCountByCondition(DynamicDBValues dy);
    
	List<Download> queryListByCondition(DynamicDBValues dy);
}