package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.model.AboutArticle;
import com.cloudeasy.model.Innovate;
import com.cloudeasy.model.InnovateWithBLOBs;

public interface InnovateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int insert(InnovateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int insertSelective(InnovateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    InnovateWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InnovateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(InnovateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innovate_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Innovate record);
    
    
    List<InnovateWithBLOBs> queryForList(InnovateWithBLOBs record);
}