package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.MovePicture;
import com.cloudeasy.model.NewsHonour;
import com.cloudeasy.model.Picture;

public interface MovePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int insert(MovePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int insertSelective(MovePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    MovePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MovePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovePicture record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int queryByCount(BaseDTO model);
    /**
     * 获取所有图片
     * @param flag
     * @return list
     */
    List<MovePicture> queryForList(BaseDTO model);
    
    /**
     * 获取所有图片
     * @param flag
     * @return list
     */
    List<MovePicture> findForList(MovePicture record);
}