package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.News;
import com.cloudeasy.model.NewsType;
import com.cloudeasy.mybatis.DynamicDBValues;
import com.cloudeasy.mybatis.DynamicParameter;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(News record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int findByCount(BaseDTO model);
    /**
     * 获取所有风采
     * @param flag
     * @return list
     */
    List<News> findForList(BaseDTO model);
    
	/**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);
    
    /**
     * 新闻列表
     * @param model
     * @return
     */
	List<News> queryByList(BaseDTO model);
	
	List<News> queryTopFive(DynamicDBValues dy);
	
	 /**
     * 总条数
     * @param model
     * @return int
     */
    int showNewsCount(BaseDTO model);
    /**
     * 获取所有风采
     * @param flag
     * @return list
     */
    List<News> showNewsList(BaseDTO model);
    
    List<News> frontNewsBySeq(DynamicDBValues dy);
	
}