package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.NewsType;

public interface NewsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    int insert(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    int insertSelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    NewsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsType record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type_tbl
     *
     * @mbggenerated
     */
    List<NewsType> showNewsTypeList(); 
    
    
	/**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);
    
    /**
     * 新闻类别列表
     * @param model
     * @return
     */
	List<NewsType> queryByList(BaseDTO model);
	
    /**
     * 新闻类别是否存在
     * @param model
     * @return
     */
    public int isCategoryName(BaseDTO model);
	
	/**
	 * 根据key找到新闻类别名称
	 * @param id
	 * @return
	 */
	String selectNameByKey(Integer id);
    
}