package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.NewsHonour;

public interface NewsHonourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int insert(NewsHonour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int insertSelective(NewsHonour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    NewsHonour selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsHonour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsHonour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_honour_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsHonour record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int queryByCount(BaseDTO model);
    /**
     * 获取所有风采
     * @param flag
     * @return list
     */
    List<NewsHonour> queryForList(BaseDTO model);
    
    /**
     * 批量删除
     * @param list
     * @return int
     */
    int batchDelete(List<Integer> list);
}