package com.cloudeasy.dao;

import com.cloudeasy.model.NewsVideo;

public interface NewsVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int insert(NewsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int insertSelective(NewsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    NewsVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_video_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsVideo record);
}