package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.NewsHonour;
import com.cloudeasy.model.Picture;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    Picture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Picture record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int queryByCount(BaseDTO model);
    /**
     * 获取所有图片
     * @param flag
     * @return list
     */
    List<Picture> queryForList(BaseDTO model);
    
    /**
     * 获取所有图片
     * @param flag
     * @return list
     */
    List<Picture> findForList(Picture record);
}