package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.NewsHonour;
import com.cloudeasy.model.QuesAnsw;

public interface QuesAnswMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    int insert(QuesAnsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    int insertSelective(QuesAnsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    QuesAnsw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuesAnsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ques_answ_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuesAnsw record);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    int queryByCount(BaseDTO model);
    /**
     * 获取所有风采
     * @param flag
     * @return list
     */
    List<QuesAnsw> queryForList(BaseDTO model);
    
    
    List<QuesAnsw> queryForListByBrandId(BaseDTO model);
    
    int queryForCountByBrandId(BaseDTO model);
}