package com.cloudeasy.dao;

import com.cloudeasy.model.RoleResource;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResource record);
    
    int deleteByRoleResource(RoleResource record);
}