package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.Sku;

public interface SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sku record);
    /**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);

    
	List<Sku> queryByList(BaseDTO model);

	
	/**
	 * 获取所有商品Sku
	 * @param model
	 * @return
	 */
	List<Sku> findAllSku(BaseDTO model);
	
	
	List<Sku> findAllSkuByBrandId(Sku sku);
}