package com.cloudeasy.dao;

import java.util.List;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.SubBrand;

public interface SubBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    int insert(SubBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    int insertSelective(SubBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    SubBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SubBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_brand_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubBrand record);
    
    /**
     * 名称是否存在
     * @param model
     * @return
     */
    public int isBrandName(BaseDTO model);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(BaseDTO model);
    
    List<SubBrand> queryByList(BaseDTO model);
    
    List<SubBrand> findByList();
    
}