package com.cloudeasy.dao;

import java.util.List;
import java.util.Map;

import com.cloudeasy.dto.BaseDTO;
import com.cloudeasy.model.Area;
import com.cloudeasy.model.Tag;
import com.cloudeasy.model.TagRelation;

public interface TagRelationMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    int insert(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    int insertSelective(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    TagRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_words_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagRelation record);
    
    List<TagRelation> queryByList(Map params);
    
    /**
     * 总条数
     * @param model
     * @return int
     */
    public int queryByCount(Map params);

	/** 
	 * TODO
	 * @param params
	 * void 
	 */
	void deleteByRelationByParam(Map params);
	
 
}